# Site settings
name: Sushanth Samala
title: Sushanth Samala | Software Engineer
description: I'm Sushanth Samala, Computer Science graduate student at New York University, Courant Institute of Mathematical Science.
url: https://sushanthsamala.tech
baseurl: ''
email: sushanthsamala@gmail.com
cover: https://sushanthsamala.tech/img/og.png
logo: https://sushanthsamala.tech/img/emojis/technologist.png
resume: https://sushanthsamala.tech/sushanth_samala_SWE2021.pdf
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sushanthsamala
  - title: github
    url: https://github.com/sushanthsamala
  - title: email
    url: mailto:sushanthsamala@gmail.com

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
